const axios = require('axios');

exports.config = {
    name: 'blackbox',
    author: 'AceGerome',
    description: 'Chat with Blackbox AI.',
    category: 'ai',
    link: ['/blackbox'],
    method: 'get' 
};

exports.initialize = async function ({ req, res }) {
    try {
        const { message } = req.query;

        if (!message || typeof message !== 'string') {
            return res.status(400).json({
                status: false,
                code: 400,
                message: 'Invalid request. "message" query parameter must be a non-empty string.'
            });
        }

        const response = await axios.post('https://api.blackbox.ai/api/chat', {
            messages: [{ id: null, content: message, role: 'user' }],
            id: null,
            previewToken: null,
            userId: null,
            codeModelMode: true,
            agentMode: {},
            trendingAgentMode: {},
            isMicMode: false,
            isChromeExt: false,
            githubToken: null
        });

        const cleanedResponse = JSON.parse(
            JSON.stringify(response.data).replace(
                /Generated by BLACKBOX\.AI, try unlimited chat https:\/\/www\.blackbox\.ai\\n\\n/g,
                ''
            )
        );

        res.status(200).json({
            status: true,
            code: 200,
            response: cleanedResponse
        });
    } catch (error) {
        console.error('Error interacting with Blackbox AI:', error.message);
        res.status(500).json({
            status: false,
            code: 500,
            message: 'Failed to process the request.',
            details: error.message
        });
    }
};